database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:dwapp/project

  properties:
      charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.hbm2ddl.auto: create-drop
      hibernate.show_sql: false

    # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

    # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

    # the minimum number of connections to keep open
  minSize: 8

    # the maximum number of connections to keep open
  maxSize: 32

    # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

http:
  rootPath: /api/*  # Default is /*
